// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/harbour-wave/harbour-wave-backend/internal/config"
	"github.com/harbour-wave/harbour-wave-backend/internal/handler"
	"github.com/harbour-wave/harbour-wave-backend/internal/platform"
	"github.com/harbour-wave/harbour-wave-backend/internal/repository"
	"github.com/harbour-wave/harbour-wave-backend/internal/service"
)

import (
	_ "github.com/harbour-wave/harbour-wave-backend/docs"
	_ "strings"
)

// Injectors from wire.go:

// InitializeServer generates the dependency graph for our application.
func InitializeServer() (*Server, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	logger := ProvideLogger(configConfig)
	db, err := ProvideDB(configConfig, logger)
	if err != nil {
		return nil, err
	}
	authService := service.NewAuthService(configConfig)
	adminRepository := repository.NewAdminRepository(db)
	slotRepository := repository.NewSlotRepository(db)
	bookingRepository := repository.NewBookingRepository(db)
	dateBlockRepository := repository.NewDateBlockRepository(db)
	systemRepository := repository.NewSystemRepository(db)
	availabilityService := service.NewAvailabilityService(slotRepository, bookingRepository, dateBlockRepository, systemRepository)
	availabilityHandler := handler.NewAvailabilityHandler(availabilityService, logger)
	pricingService := service.NewPricingService()
	clock := platform.NewClock()
	bookingService := service.NewBookingService(db, bookingRepository, slotRepository, dateBlockRepository, systemRepository, pricingService, clock)
	bookingHandler := handler.NewBookingHandler(bookingService, logger)
	paymentGateway := ProvidePaymentGateway(configConfig, logger)
	checkoutService := service.NewCheckoutService(bookingService, bookingRepository, pricingService, paymentGateway, configConfig, clock)
	checkoutHandler := handler.NewCheckoutHandler(checkoutService, logger)
	emailService := service.NewEmailService(configConfig, logger)
	posterClient := ProvidePosterClient(configConfig, logger)
	webhookService := service.NewWebhookService(bookingRepository, emailService, posterClient, logger)
	webhookHandler := handler.NewWebhookHandler(paymentGateway, webhookService, logger)
	adminService := service.NewAdminService(db, bookingRepository, slotRepository, dateBlockRepository, systemRepository, pricingService, clock)
	adminHandler := handler.NewAdminHandler(adminService, logger)
	engine := ProvideRouter(configConfig, logger, authService, adminRepository, availabilityHandler, bookingHandler, checkoutHandler, webhookHandler, adminHandler)
	server := &Server{
		Config:     configConfig,
		Log:        logger,
		DB:         db,
		Router:     engine,
		SystemRepo: systemRepository,
		BookingSvc: bookingService,
	}
	return server, nil
}
