// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/bookings/{bookingId}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin endpoint to force cancel a booking.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Cancel a booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Booking ID (UUID)",
                        "name": "bookingId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancellation reason",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminCancelBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminCancelBookingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            }
        },
        "/admin/bookings/{bookingId}/price": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin endpoint to manually override the price of a booking.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Override booking price",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Booking ID (UUID)",
                        "name": "bookingId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Override details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminPriceOverrideRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminPriceOverrideResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            }
        },
        "/admin/dates/{date}/block": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin endpoint to block bookings for an entire date.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Block an entire date",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Block reason",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminBlockDateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminBlockDateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin endpoint to remove a block on an entire date.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Unblock an entire date",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminUnblockDateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            }
        },
        "/admin/slots/{date}/{time}/{route}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin endpoint to create a slot for a given date/time/route or update its capacities.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create or update a slot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Time in HH:MM format",
                        "name": "time",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Route name",
                        "name": "route",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Capacity payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminUpsertSlotRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminUpsertSlotResponse"
                        }
                    },
                    "400": {
                        "description": "INVALID_DATE, INVALID_TIME, INVALID_ROUTE, or INVALID_INPUT",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            }
        },
        "/admin/slots/{date}/{time}/{route}/block": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin endpoint to block bookings for a specific date, time, and route.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Block a specific slot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Time in HH:MM format",
                        "name": "time",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Route name",
                        "name": "route",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Block reason",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminBlockSlotRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminBlockSlotResponse"
                        }
                    },
                    "400": {
                        "description": "INVALID_DATE, INVALID_TIME, or INVALID_ROUTE",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin endpoint to remove a block on a specific date, time, and route.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Unblock a specific slot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Time in HH:MM format",
                        "name": "time",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Route name",
                        "name": "route",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminUnblockSlotResponse"
                        }
                    },
                    "400": {
                        "description": "INVALID_DATE, INVALID_TIME, or INVALID_ROUTE",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            }
        },
        "/admin/slots/{date}/{time}/{route}/bookings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin endpoint returning all bookings (any status) for a specific date/time/route slot.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List bookings for a slot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Time in HH:MM format",
                        "name": "time",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Route name",
                        "name": "route",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminSlotBookingsResponse"
                        }
                    },
                    "400": {
                        "description": "INVALID_DATE, INVALID_TIME, or INVALID_ROUTE",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            }
        },
        "/admin/system/bookings-enabled": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin endpoint to enable or disable the creation of all new bookings.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Toggle global booking kill-switch",
                "parameters": [
                    {
                        "description": "Kill-switch payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminSetBookingsEnabledRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminSetBookingsEnabledResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            }
        },
        "/availability/{month}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns daily availability for a given month",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "availability"
                ],
                "summary": "Get monthly availability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Month in YYYY-MM format",
                        "name": "month",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AvailabilityMonthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            }
        },
        "/bookings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all bookings (any status) belonging to the current user, newest first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "List the authenticated user's bookings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.MyBookingsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a pending booking and holds slot capacity. Requires idempotency key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Create a new booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Idempotency Key",
                        "name": "X-Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Booking payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.CreateBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.CreateBookingResponse"
                        }
                    },
                    "400": {
                        "description": "INVALID_INPUT",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "NOT_AUTHENTICATED",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "SLOT_TAKEN",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "422": {
                        "description": "VALIDATION_FAILED, DATE_BLOCKED, or SLOT_BLOCKED",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "BOOKINGS_DISABLED or SERVICE_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            }
        },
        "/bookings/by-session/{sessionId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns minimal status info while pending, or the full booking once confirmed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Get booking by session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.BookingBySessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            }
        },
        "/checkout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates a payment gateway checkout URL for a pending booking.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checkout"
                ],
                "summary": "Create checkout session",
                "parameters": [
                    {
                        "description": "Checkout Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.CreateCheckoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.CreateCheckoutResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "410": {
                        "description": "BOOKING_EXPIRED",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "422": {
                        "description": "BOOKING_NOT_PENDING",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            }
        },
        "/payment/webhook": {
            "post": {
                "description": "Receives payment status updates via HMAC-secured webhook.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Payment gateway webhook",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "INVALID_SIGNATURE or CANNOT_READ_BODY",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "500": {
                        "description": "WEBHOOK_PROCESSING_FAILED",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            }
        },
        "/slots/{date}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all available and blocked slots for a specific date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "availability"
                ],
                "summary": "Get slots for a date",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.SlotsForDateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns whether bookings are globally available or fully blocked",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "availability"
                ],
                "summary": "Get booking status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.BookingStatusResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminBlockDateRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminBlockDateResponse": {
            "type": "object",
            "properties": {
                "blocked": {
                    "type": "boolean"
                },
                "blockedAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminBlockSlotRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminBlockSlotResponse": {
            "type": "object",
            "properties": {
                "blocked": {
                    "type": "boolean"
                },
                "blockedAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "routeName": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminBookingListEntry": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "effectiveAmount": {
                    "type": "number"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "posterIncomingOrderId": {
                    "type": "integer"
                },
                "posterIncomingTransactionId": {
                    "type": "integer"
                },
                "quantities": {
                    "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.Quantities"
                },
                "routeName": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "totalAmount": {
                    "type": "number"
                },
                "userEmail": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminCancelBookingRequest": {
            "type": "object",
            "required": [
                "reason"
            ],
            "properties": {
                "reason": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminCancelBookingResponse": {
            "type": "object",
            "properties": {
                "bookingId": {
                    "type": "string"
                },
                "cancelledAt": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminPriceOverrideRequest": {
            "type": "object",
            "required": [
                "reason"
            ],
            "properties": {
                "reason": {
                    "type": "string",
                    "minLength": 5
                },
                "totalAmount": {
                    "description": "nil clears the override",
                    "type": "number"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminPriceOverrideResponse": {
            "type": "object",
            "properties": {
                "bookingId": {
                    "type": "string"
                },
                "effectiveAmount": {
                    "type": "number"
                },
                "overrideReason": {
                    "type": "string"
                },
                "priceOverride": {
                    "type": "number"
                },
                "totalAmount": {
                    "type": "number"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminSetBookingsEnabledRequest": {
            "type": "object",
            "required": [
                "enabled"
            ],
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminSetBookingsEnabledResponse": {
            "type": "object",
            "properties": {
                "bookingsEnabled": {
                    "type": "boolean"
                },
                "reason": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminSlotBookingsResponse": {
            "type": "object",
            "properties": {
                "bookings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AdminBookingListEntry"
                    }
                },
                "date": {
                    "type": "string"
                },
                "routeName": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminUnblockDateResponse": {
            "type": "object",
            "properties": {
                "blocked": {
                    "type": "boolean"
                },
                "date": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminUnblockSlotResponse": {
            "type": "object",
            "properties": {
                "blocked": {
                    "type": "boolean"
                },
                "date": {
                    "type": "string"
                },
                "routeName": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminUpsertSlotRequest": {
            "type": "object",
            "required": [
                "capacityBig",
                "capacityMedium",
                "capacitySmall"
            ],
            "properties": {
                "capacityBig": {
                    "type": "integer",
                    "minimum": 0
                },
                "capacityMedium": {
                    "type": "integer",
                    "minimum": 0
                },
                "capacitySmall": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AdminUpsertSlotResponse": {
            "type": "object",
            "properties": {
                "blocked": {
                    "type": "boolean"
                },
                "capacityBig": {
                    "type": "integer"
                },
                "capacityMedium": {
                    "type": "integer"
                },
                "capacitySmall": {
                    "type": "integer"
                },
                "created": {
                    "type": "boolean"
                },
                "date": {
                    "type": "string"
                },
                "routeName": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AvailabilityDay": {
            "type": "object",
            "properties": {
                "availableSlots": {
                    "type": "integer"
                },
                "blocked": {
                    "type": "boolean"
                },
                "date": {
                    "type": "string"
                },
                "fullyBlocked": {
                    "type": "boolean"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.AvailabilityMonthResponse": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.AvailabilityDay"
                    }
                },
                "month": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.BookingBySessionResponse": {
            "type": "object",
            "properties": {
                "booking": {
                    "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.BookingPublicView"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.BookingPublicView": {
            "type": "object",
            "properties": {
                "contact": {
                    "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.ContactPublicView"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "quantities": {
                    "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.Quantities"
                },
                "routeName": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "totalAmount": {
                    "type": "number"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.BookingStatusResponse": {
            "type": "object",
            "properties": {
                "bookingsEnabled": {
                    "type": "boolean"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.ContactPublicView": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.ContactRequest": {
            "type": "object",
            "required": [
                "firstName",
                "lastName",
                "phone"
            ],
            "properties": {
                "email": {
                    "description": "ignored; JWT email used",
                    "type": "string"
                },
                "firstName": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "lastName": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "phone": {
                    "description": "REQUIRED",
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.CreateBookingRequest": {
            "type": "object",
            "required": [
                "contact",
                "date",
                "quantities",
                "routeName",
                "time"
            ],
            "properties": {
                "contact": {
                    "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.ContactRequest"
                },
                "date": {
                    "type": "string"
                },
                "quantities": {
                    "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.QuantitiesRequest"
                },
                "routeName": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.CreateBookingResponse": {
            "type": "object",
            "properties": {
                "bookingId": {
                    "type": "string"
                },
                "expiresAt": {
                    "type": "string"
                },
                "totalAmount": {
                    "type": "number"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.CreateCheckoutRequest": {
            "type": "object",
            "required": [
                "bookingId",
                "resultUrl"
            ],
            "properties": {
                "bookingId": {
                    "type": "string"
                },
                "resultUrl": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.CreateCheckoutResponse": {
            "type": "object",
            "properties": {
                "checkoutUrl": {
                    "type": "string"
                },
                "sessionId": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.MyBookingView": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "expiresAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "quantities": {
                    "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.Quantities"
                },
                "routeName": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "totalAmount": {
                    "type": "number"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.MyBookingsResponse": {
            "type": "object",
            "properties": {
                "bookings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.MyBookingView"
                    }
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.Quantities": {
            "type": "object",
            "properties": {
                "big": {
                    "type": "integer"
                },
                "child": {
                    "type": "integer"
                },
                "medium": {
                    "type": "integer"
                },
                "small": {
                    "type": "integer"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.QuantitiesRequest": {
            "type": "object",
            "properties": {
                "big": {
                    "type": "integer"
                },
                "child": {
                    "type": "integer"
                },
                "medium": {
                    "type": "integer"
                },
                "small": {
                    "type": "integer"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.SlotForDate": {
            "type": "object",
            "properties": {
                "availableBig": {
                    "type": "integer"
                },
                "availableMedium": {
                    "type": "integer"
                },
                "availableSmall": {
                    "type": "integer"
                },
                "blocked": {
                    "type": "boolean"
                },
                "routeName": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "totalBig": {
                    "type": "integer"
                },
                "totalMedium": {
                    "type": "integer"
                },
                "totalSmall": {
                    "type": "integer"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_internal_model.SlotsForDateResponse": {
            "type": "object",
            "properties": {
                "bookingsEnabled": {
                    "type": "boolean"
                },
                "date": {
                    "type": "string"
                },
                "dateBlocked": {
                    "type": "boolean"
                },
                "fullyBlocked": {
                    "type": "boolean"
                },
                "slots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_internal_model.SlotForDate"
                    }
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_pkg_httpx.ErrorBody": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "issues": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_harbour-wave_harbour-wave-backend_pkg_httpx.Issue"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_harbour-wave_harbour-wave-backend_pkg_httpx.Issue": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Harbour & Wave API",
	Description:      "Boat reservation backend",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
